juk

diff --git a/0x00-hello_world/0-preprocessor b/0x00-hello_world/0-preprocessor
--- a/0x00-hello_world/0-preprocessor
+++ b/0x00-hello_world/0-preprocessor
@@ -1,15 +1,2 @@
-FILE="$1"
-
-if [[ -z "$CFILE" ]]; then
-  echo "Error: Please provide a C file name as an argument."
-  exit 1
-fi
-
-gcc -E -o c "$CFILE"
-
-if [[ $? -eq 0 ]]; then
-  echo "Preprocessed $CFILE and saved output to c"
-else
-  echo "Error: Preprocessing failed!"
-  exit 1
-fi
+#!/bin/bash
+gcc -E -o c "$1" || echo "Preprocessing failed!"
